### ISSUE TITLE
The implementation of bitlinear is wrong

### ISSUE THREAD

**Issue by suzuke** [tomsanbear/bitnet-rs#1]
The implementation of bitlinear in kyegomez/BitNet is totally wrong.

Gemma, beta, and alpha are calculated using weights and input before quantization. These parameters are then utilized for weights binarization and input quantization. The binarized weights and quantized input undergo linear operations to produce the output, which is then dequantized using the previously calculated gemma, beta. It's not meaningful to calculate gemma and beta separately for quantization and dequantization stages, and even the implementation of grouping here is entirely nonsensical.

**Comment by suzuke** [comment]
The issues I mentioned have been addressed in the commit 6cdb2ea998e843b454f2fbaaef73bc6bf92c305f.

**Comment by tomsanbear** [comment]
Thanks for the info, i'll take a look at that change and adjust this implementation to match 👍
